test_casefile: test_cases.txt

evaluate_predictions: True
export_predictions: True
allow_overwriting: False
# For RN, patch size for tiled inference
rn_patch_size: [128, 128, 128]

# For AD, whether to perform inference from three orthogonal slices instead of thick/thin slices
sample_orthogonal_slices: False
# For AD/RN: thin out volumes by keeping every x slice. Should be at least 2.
slice_step_size: 8
# For AD/RN: axis for volume thinning in LPS coordinate system: sagittal, coronal, axial.
slice_step_axis: 0

# For AD, number of iterations for latent optimization.
latent_num_iters: 1200
# For AD, if train dice doesn't change this number of 10-step blocks, stop latent optimization. -1 means never stop early.
max_num_const_train_dsc: -1
